In [1]:
import pandas as pd # Import the pandas module

# Assign the data URL to the variable data_url
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'

# Load the CSV data
df = pd.read_csv(data_url, sep='\s+', header=None)

<>:7: SyntaxWarning: invalid escape sequence '\s'
<>:7: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_4713/1283948177.py:7: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv(data_url, sep='\s+', header=None)

In [2]:
#Assign column names to the DataFrame
df.columns = [
    'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE',
    'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV'
]

df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [3]:
file = 'https://raw.githubusercontent.com/prof-dana/Lecture-Code/refs/heads/main/BigDataMining/data/comp-data.csv'

df_data = pd.read_csv(file) #load csv data
df = pd.DataFrame(df_data)
df

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
1,320563,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah,NorthCarolina,38365,95000,45000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
4,121213,Bauch-Goldner,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000
5,132971,"Williamson, Schumm and Hettinger",89403 Casimer Spring,Jeremieburgh,Arkansas,62785,150000,120000,35000
6,145068,Casper LLC,340 Consuela Bridge Apt. 400,Lake Gabriellaton,Mississipi,18008,62000,120000,70000
7,205217,Kovacek-Johnston,91971 Cronin Vista Suite 601,Deronville,RhodeIsland,53461,145000,95000,35000
8,209744,Champlin-Morar,26739 Grant Lock,Lake Juliannton,Pennsylvania,64415,70000,95000,35000
9,212303,Gerhold-Maggio,366 Maggio Grove Apt. 998,North Ras,Idaho,46308,70000,120000,35000
10,214098,"Goodwin, Homenick and Jerde",649 Cierra Forks Apt. 078,Rosaberg,Tenessee,47743,45000,120000,55000
11,231907,Hahn-Moore,18115 Olivine Throughway,Norbertomouth,NorthDakota,31415,150000,10000,162000
12,242368,"Frami, Anderson and Donnelly",182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
13,268755,Walsh-Haley,2624 Beatty Parkways,Goodwinmouth,RhodeIsland,31919,55000,120000,35000
14,273274,McDermott PLC,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000

In [4]:
df.head() #default is 5

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
1,320563,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah,NorthCarolina,38365,95000,45000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
4,121213,Bauch-Goldner,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000

In [5]:
df.head(3).T # Transpose the first 3 rows, swapping rows and columns

,0,1,2
account,211829,320563,648336
name,"Kerluke, Koepp and Hilpert",Walter-Trantow,"Bashirian, Kunde and Price"
street,34456 Sean Highway,1311 Alvis Tunnel,62184 Schamberger Underpass Apt. 231
city,New Jaycob,Port Khadijah,New Lilianland
state,Texas,NorthCarolina,Iowa
postal-code,28752,38365,76517
Jan,10000,95000,91000
Feb,62000,45000,120000
Mar,35000,35000,35000

In [6]:
df.tail(4)

,account,name,street,city,state,postal-code,Jan,Feb,Mar
11,231907,Hahn-Moore,18115 Olivine Throughway,Norbertomouth,NorthDakota,31415,150000,10000,162000
12,242368,"Frami, Anderson and Donnelly",182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
13,268755,Walsh-Haley,2624 Beatty Parkways,Goodwinmouth,RhodeIsland,31919,55000,120000,35000
14,273274,McDermott PLC,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000

In [7]:
df["account"]

0     211829
1     320563
2     648336
3     109996
4     121213
5     132971
6     145068
7     205217
8     209744
9     212303
10    214098
11    231907
12    242368
13    268755
14    273274
Name: account, dtype: int64

In [8]:
df[["account", "street", "state"]].head(3)

   account                                street          state
0   211829                    34456 Sean Highway          Texas
1   320563                     1311 Alvis Tunnel  NorthCarolina
2   648336  62184 Schamberger Underpass Apt. 231           Iowa

In [9]:
df[:3]

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
1,320563,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah,NorthCarolina,38365,95000,45000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000

In [10]:
df[["name","city","state"]][7:13]

                            name             city         state
7               Kovacek-Johnston       Deronville   RhodeIsland
8                 Champlin-Morar  Lake Juliannton  Pennsylvania
9                 Gerhold-Maggio        North Ras         Idaho
10   Goodwin, Homenick and Jerde         Rosaberg      Tenessee
11                    Hahn-Moore    Norbertomouth   NorthDakota
12  Frami, Anderson and Donnelly      East Davian          Iowa

In [11]:
df.iloc[7:13, [1,3,4]]

                            name             city         state
7               Kovacek-Johnston       Deronville   RhodeIsland
8                 Champlin-Morar  Lake Juliannton  Pennsylvania
9                 Gerhold-Maggio        North Ras         Idaho
10   Goodwin, Homenick and Jerde         Rosaberg      Tenessee
11                    Hahn-Moore    Norbertomouth   NorthDakota
12  Frami, Anderson and Donnelly      East Davian          Iowa

In [12]:
df = df.drop(1) #Delete the row with index label 1
df.head()

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
4,121213,Bauch-Goldner,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000
5,132971,"Williamson, Schumm and Hettinger",89403 Casimer Spring,Jeremieburgh,Arkansas,62785,150000,120000,35000

In [13]:
import numpy as np
df.drop(np.arange(4,10), inplace=True)#inplace=True deletes rows directly from the original DataFrame
df

,account,name,street,city,state,postal-code,Jan,Feb,Mar
0,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
2,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
10,214098,"Goodwin, Homenick and Jerde",649 Cierra Forks Apt. 078,Rosaberg,Tenessee,47743,45000,120000,55000
11,231907,Hahn-Moore,18115 Olivine Throughway,Norbertomouth,NorthDakota,31415,150000,10000,162000
12,242368,"Frami, Anderson and Donnelly",182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
13,268755,Walsh-Haley,2624 Beatty Parkways,Goodwinmouth,RhodeIsland,31919,55000,120000,35000
14,273274,McDermott PLC,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000

In [14]:
df.drop("account",axis=1).head(3)  #Remove account column

,name,street,city,state,postal-code,Jan,Feb,Mar
0,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
2,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000

In [15]:
df.drop(["account", "name"], axis=1,inplace = True) # Delete the account and name columns directly
df.head(3)

,street,city,state,postal-code,Jan,Feb,Mar
0,34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
2,62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000

In [16]:
df[df['Jan']>= 150000]

,street,city,state,postal-code,Jan,Feb,Mar
11,18115 Olivine Throughway,Norbertomouth,NorthDakota,31415,150000,10000,162000
12,182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
14,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000

In [17]:
df[(df['Jan']>= 10000) & (df['state'] == 'Iowa')]

,street,city,state,postal-code,Jan,Feb,Mar
2,62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
12,182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000

In [18]:
df_sort = df.sort_values(by="state")#Ascending Order
df_sort.head()

,street,city,state,postal-code,Jan,Feb,Mar
14,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000
2,62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
12,182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
3,155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
11,18115 Olivine Throughway,Norbertomouth,NorthDakota,31415,150000,10000,162000

In [19]:
df.sort_values(by="city", ascending=False).head()#Descending Order

,street,city,state,postal-code,Jan,Feb,Mar
10,649 Cierra Forks Apt. 078,Rosaberg,Tenessee,47743,45000,120000,55000
11,18115 Olivine Throughway,Norbertomouth,NorthDakota,31415,150000,10000,162000
2,62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
0,34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
14,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000

In [20]:
df.sort_values(by=["city","state"]).head()

,street,city,state,postal-code,Jan,Feb,Mar
12,182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
13,2624 Beatty Parkways,Goodwinmouth,RhodeIsland,31919,55000,120000,35000
3,155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
14,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000
0,34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000

In [21]:
ipl_data = 'https://raw.githubusercontent.com/prof-dana/Lecture-Code/refs/heads/main/BigDataMining/data/ipl_data.csv'

df = pd.read_csv(ipl_data)
df

      Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690

In [22]:
df.groupby("Team")["Points"].sum()

Team
Devils    1536
Kings     2285
Riders    3049
Royals    1505
kings      812
Name: Points, dtype: int64

In [23]:
multi_groupby = df.groupby(["Team", "Year"])["Points"].sum()
multi_groupby

Team    Year
Devils  2014    863
        2015    673
Kings   2014    741
        2016    756
        2017    788
Riders  2014    876
        2015    789
        2016    694
        2017    690
Royals  2014    701
        2015    804
kings   2015    812
Name: Points, dtype: int64

In [24]:
multi_groupby["Riders"]

Year
2014    876
2015    789
2016    694
2017    690
Name: Points, dtype: int64

In [25]:
multi_groupby["Kings":"Royals"]

Team    Year
Kings   2014    741
        2016    756
        2017    788
Riders  2014    876
        2015    789
        2016    694
        2017    690
Royals  2014    701
        2015    804
Name: Points, dtype: int64

In [26]:
df1 = pd.read_csv("https://raw.githubusercontent.com/prof-dana/Lecture-Code/refs/heads/main/BigDataMining/data/sales-jan-2014.csv")
df2 = pd.read_csv("https://raw.githubusercontent.com/prof-dana/Lecture-Code/refs/heads/main/BigDataMining/data/sales-feb-2014.csv")
print(df1.shape)
print(df2.shape)

(134, 7)
(108, 7)

In [27]:
df_list = [df1, df2]
result = pd.concat(df_list, axis=0) # Concatenate vertically along the rows
result = result.reset_index(drop=True) # Reset the index and discard the old index
print(result.shape)

(242, 7)

In [28]:
result.head()

,account number,name,sku,quantity,unit price,ext price,date
0,740150,Barton LLC,B1-20000,39,86.69,3380.91,2014-01-01 07:21:51
1,714466,Trantow-Barrows,S2-77896,-1,63.16,-63.16,2014-01-01 10:00:47
2,218895,Kulas Inc,B1-69924,23,90.70,2086.10,2014-01-01 13:24:58
3,307599,"Kassulke, Ondricka and Metz",S1-65481,41,21.05,863.05,2014-01-01 15:05:22
4,412290,Jerde-Hilpert,S2-34077,6,83.21,499.26,2014-01-01 23:26:55

In [29]:
rows = result.shape[0]

newCol = np.random.uniform(0,1, rows).reshape(-1,1)
newCol[:5]

array([[0.40952298],
       [0.88269432],
       [0.73213168],
       [0.65377761],
       [0.66306282]])

In [30]:
newCol = pd.DataFrame(newCol, columns=['Random'], index=result.index) #transform np array to DataFrame
result2 = pd.concat([result, newCol], axis=1)
result2.head()

,account number,name,sku,quantity,unit price,ext price,date,Random
0,740150,Barton LLC,B1-20000,39,86.69,3380.91,2014-01-01 07:21:51,0.409523
1,714466,Trantow-Barrows,S2-77896,-1,63.16,-63.16,2014-01-01 10:00:47,0.882694
2,218895,Kulas Inc,B1-69924,23,90.70,2086.10,2014-01-01 13:24:58,0.732132
3,307599,"Kassulke, Ondricka and Metz",S1-65481,41,21.05,863.05,2014-01-01 15:05:22,0.653778
4,412290,Jerde-Hilpert,S2-34077,6,83.21,499.26,2014-01-01 23:26:55,0.663063

In [31]:
result['Random'] = np.random.uniform(0,1, rows)
result.head()

,account number,name,sku,quantity,unit price,ext price,date,Random
0,740150,Barton LLC,B1-20000,39,86.69,3380.91,2014-01-01 07:21:51,0.799686
1,714466,Trantow-Barrows,S2-77896,-1,63.16,-63.16,2014-01-01 10:00:47,0.636054
2,218895,Kulas Inc,B1-69924,23,90.70,2086.10,2014-01-01 13:24:58,0.852494
3,307599,"Kassulke, Ondricka and Metz",S1-65481,41,21.05,863.05,2014-01-01 15:05:22,0.920433
4,412290,Jerde-Hilpert,S2-34077,6,83.21,499.26,2014-01-01 23:26:55,0.046174